version: "3.8"

services:
  spring-app:
    container_name: spring-app-ana
    build: 
      context: ./spring-boot-todo-list-main
    ports:
      - "8082:8080" # Maps the container's 8080 into the host's 8082
    networks:
      - ana-net

  ana-postgres-base:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=anabase
      - POSTGRES_USER=anadmin
      - POSTGRES_PASSWORD=anapass
    # ports:
    #   - "5432:5432"
    networks:
      - ana-net
    volumes:
      - postgres-data:/var/lib/postgresql/data  # The volume for my database

networks:
  ana-net:
    driver: bridge

volumes:
  postgres-data: