name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      env: 
        DOCKER_USER: ${{secrets.DOCKERHUB_TOKEN}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker Image
      run: docker build spring-boot-todo-list-main --file spring-boot-todo-list-main/Dockerfile --tag anastasijapetrova88704/kiii-project:latest
    
    - name: Docker Push Image
      run: docker push ${{secrets.DOCKERHUB_USER}}/kiii-project:latest

        
